from pycrispr.fasta_sequences import *

import pytest

empty_fasta = ""

single_fasta = """>sequence1
ACTCCCCGTGCGCGCCCGGCCCGTAGCGTCCTCGTCGCCGCCCCTCGTCTCGCAGCCGCAGCCCGCGTGG
ACGCTCTCGCCTGAGCGCCGCGGACTAGCCCGGGTGGCC
"""

multi_fasta = """>sequence1
ACTCCCCGTGCGCGCCCGGCCCGTAGCGTCCTCGTCGCCGCCCCTCGTCTCGCAGCCGCAGCCCGCGTGG
ACGCTCTCGCCTGAGCGCCGCGGACTAGCCCGGGTGGCC
>sequence2
CAGTCCGGCAGCGCCGGGGTTAAGCGGCCCAAGTAAACGTAGCGCAGCGATCGGCGCCGGAGATTCGCGA
ACCCGACACTCCGCGCCGCCCGCCGGCCAGGACCCGCGGCGCGATCGCGGCGCCGCGCTACAGCCAGCCT
CACTGGCGCGCGGGCGAGCGCACGGGCGCTC
>sequence3
CACGACAGGCCCGCTGAGGCTTGTGCCAGACCTTGGAAACCTCAGGTATATACCTTTCCAGACGCGGGAT
CTCCCCTCCCC
>sequence4
CAGCAGACATCTGAATGAAGAAGAGGGTGCCAGCGGGTATGAGGAGTGCATTATCGTTAATGGGAACTTC
AGTGACCAGTCCTCAGACACGAAGGATGCTCCCTCACCCCCAGTCTTGGAGGCAATCTGCACAGAGCCAG
TCTGCACACC
"""

headers = ["sequence1", "sequence2", "sequence3", "sequence4"]
seqs = ["ACTCCCCGTGCGCGCCCGGCCCGTAGCGTCCTCGTCGCCGCCCCTCGTCTCGCAGCCGCAGCCCGCGTGG\
ACGCTCTCGCCTGAGCGCCGCGGACTAGCCCGGGTGGCC", 
"CAGTCCGGCAGCGCCGGGGTTAAGCGGCCCAAGTAAACGTAGCGCAGCGATCGGCGCCGGAGATTCGCGA\
ACCCGACACTCCGCGCCGCCCGCCGGCCAGGACCCGCGGCGCGATCGCGGCGCCGCGCTACAGCCAGCCT\
CACTGGCGCGCGGGCGAGCGCACGGGCGCTC",
"CACGACAGGCCCGCTGAGGCTTGTGCCAGACCTTGGAAACCTCAGGTATATACCTTTCCAGACGCGGGAT\
CTCCCCTCCCC",
"CAGCAGACATCTGAATGAAGAAGAGGGTGCCAGCGGGTATGAGGAGTGCATTATCGTTAATGGGAACTTC\
AGTGACCAGTCCTCAGACACGAAGGATGCTCCCTCACCCCCAGTCTTGGAGGCAATCTGCACAGAGCCAG\
TCTGCACACC"]


def test_is_empty():
    assert not FastaSequences(file="test/multi.fasta").is_empty()
    
def test_validate_fasta():
    with pytest.raises(ValueError):
        FastaSequences(file="test/empty.fasta")
    with pytest.raises(ValueError):
        FastaSequences(string="")

def test_load_file():
    f = FastaSequences(file="test/multi.fasta")
    i = 0
    for s in f:
        assert s.header == headers[i]
        assert s.seq == seqs[i]
        i += 1

def test_load_string():
    f = FastaSequences(string=multi_fasta)
    i = 0
    for s in f:
        assert s.header == headers[i]
        assert s.seq == seqs[i]
        i += 1
            
